SELECT * FROM customer

-- what is the total revenue generated by male vs female customers
SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender

--Which customer used a discount but still purchased more than the average amount
SELECT c.customer_id, c.purchase_amount
FROM customer c
WHERE discount_applied = 'Yes'
AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer) 

--Which is the top 5 products with the highest average review rating
WITH cust AS(
SELECT item_purchased, AVG(review_rating) AS avg_rating
FROM customer
GROUP BY item_purchased
),
cust2 AS ( SELECT item_purchased, avg_rating, RANK() OVER(ORDER BY avg_rating DESC) AS row_ranks
FROM cust
)
SELECT item_purchased, avg_rating
FROM cust2
WHERE row_ranks <= 5

--Compare the average purchase amount between standard and express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount),2) as avg_purchase_amount
FROM customer
GROUP BY shipping_type
HAVING shipping_type IN ('Standard', 'Express')

--Do subscribed customers spend more? Compare average spend 
--and total revenue between subscribers and non subscribers
SELECT subscription_status, count(customer_id) AS total_customers,
round(AVG(purchase_amount),2) AS average_spend, 
SUM(purchase_amount) AS total_spend
FROM customer
GROUP BY subscription_status

--Which 5 products have the highest percentage of purchases 
--with discounts applied
WITH cust1 AS(SELECT item_purchased, 
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2) AS percentage_purchases
FROM customer
GROUP BY item_purchased),
cust2 AS (SELECT item_purchased, percentage_purchases, RANK() OVER(ORDER BY percentage_purchases DESC) AS row_ranks
FROM cust1)
SELECT item_purchased, percentage_purchases
FROM cust2
WHERE row_ranks <=5

--Segment customers into new, returning and loyal based on their total
--number of previous purchases, and show the count of each segment
WITH cust AS (SELECT customer_id,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning' 
	ELSE 'Loyal'
	END AS customer_segment
FROM customer)
SELECT customer_segment, count(*) as number_of_customers
FROM cust
GROUP BY customer_segment

-- what are the top 3 most purchased products within each category
WITH cust AS(
SELECT category,item_purchased, COUNT(item_purchased) AS purchased_count,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS rank_product
FROM customer
GROUP BY category, item_purchased
)
SELECT category, item_purchased, purchased_count, rank_product
FROM cust
WHERE rank_product <=3

-- Are customers who are repeat buyers(more than 5 previous purchases) also 
--likely to subscribe
SELECT subscription_status, COUNT(customer_id) AS repeated_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status

-- what is the revenue contribution of each age group
SELECT SUM(purchase_amount) AS total_revenue, age_group
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC